# Generated by Django 3.1.2 on 2020-10-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201016_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='myapp/images', verbose_name='Изображение'),
        ),
    ]
